name: (API) Check Package Version

on:
  pull_request:
    branches:
      - master
    paths:
      - "server/src/**"

jobs:
  check-unchanged:
    name: Check Unchanged Package Version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Get master npm version
        id: master-package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: server

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Get current npm version
        id: current-package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: server

      - name: Compare both versions
        if: steps.master-package-version.outputs.current-version == steps.current-package-version.outputs.current-version
        run: |
          echo "Warning: API code has changed, but package.json version is unchanged (${{steps.master-package-version.outputs.current-version}})"
          exit 1
