name: Build App Image

on:
  push:
    branches:
      - staging
    paths:
      - 'app/**'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build and Push To Docker Hub
        env:
          ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}
        run: |
          cd app
          docker build . --file Dockerfile --tag wiseoldman/app:latest --build-arg REACT_APP_ANALYTICS_TRACKING_ID=$ANALYTICS_TRACKING_ID
          docker push wiseoldman/app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: 'Rebuild NGINX and Deploy'
        uses: wise-old-man/nginx-deploy-config@test
