name: Build Trailblazer App Image

on:
  push:
    branches:
      - league/trailblazer
    paths:
      - 'app/**'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build and Push To Docker Hub
        env:
          ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}
        run: |
          cd app
          docker build . --file Dockerfile --tag wiseoldman/trailblazer-app:latest --build-arg REACT_APP_ANALYTICS_TRACKING_ID=$ANALYTICS_TRACKING_ID
          docker push wiseoldman/trailblazer-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRAILBLAZER_DO_HOST }}
          username: ${{ secrets.TRAILBLAZER_DO_USER }}
          passphrase: ${{ secrets.TRAILBLAZER_DO_SSH_PASS }}
          key: ${{ secrets.TRAILBLAZER_DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker-compose pull
            docker-compose up --build -d
