name: Continuous Deployment (v2)

on:
  push:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  build-api-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: server

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build Docker Images and Push To Docker Hub
        run: |
          cd server
          docker build . -f Dockerfile -t wiseoldman/api-v2:latest -t wiseoldman/api-v2:${{steps.package-version.outputs.current-version}}
          docker push -a wiseoldman/api-v2
  deploy:
    name: Pull & Restart Docker Container
    needs: [build-api-image]
    runs-on: ubuntu-latest
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          passphrase: ${{ secrets.DO_SSH_PASS }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker image rm wiseoldman/api-v2
            docker-compose pull api-v2
            docker-compose up -d --no-deps --build api-v2
